services:
  mongo:
    image: mongo:7
    container_name: planit-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - planit-mongo-data:/data/db

  redis:
    image: redis:7.4
    container_name: planit-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: >
      redis-server
      --appendonly yes
      --appendfsync everysec
      --requirepass localpass
    volumes:
      - planit-redis-data:/data

volumes:
  planit-redis-data:
  planit-mongo-data:
